api-version: 2019-12-01
location: uksouth
name: PantryPal
properties:
  containers:
    - name: streamlitapp
      properties:
        image: pantrypalregistry.azurecr.io/pantrypal:v1
        ports:
          - port: 80
            protocol: TCP
          - port: 443
            protocol: TCP
        resources:
          requests:
            cpu: 2.0
            memoryInGB: 1.5
  imageRegistryCredentials:
    - server: pantrypalregistry.azurecr.io
      username: pantrypalregistry
      password: FUEigBFPEUpOM/4ajeCmF6lxJDixKiqHgv9BWsUQkY+ACRAYwfEv
  restartPolicy: Never
  ipAddress:
    ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
    type: Public
    dnsNameLabel: pantrypal
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups
